### ISSUE TITLE
Make Stable Diffusion hello world

### ISSUE THREAD

**Issue by Bugsbugme** [kris-classes/restart#14]
Stable Diffusion github - https://github.com/CompVis/stable-diffusion
Requires Conda - https://docs.conda.io/en/latest/

Some videos on Stable Diffusion and how it works:
[How AI Image Generators Work (Stable Diffusion / Dall-E) - Computerphile](https://youtu.be/1CIpzeNxIhU) 
[Stable Diffusion in Code (AI Image Generation) - Computerphile](https://youtu.be/-lz30by8-sU)

Huggingface Google Colab notebook for Stable Diffusion using diffusers
https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_diffusion.ipynb

**Comment by Bugsbugme** [comment]
Created Google Colab notebook and generated image with Stable Diffusion

**Comment by krp** [comment]
Great resources!
